application: playgrub
version: 40
runtime: python
api_version: 1

handlers:
- url: /admin/.*
  script: admin.py
  login: admin

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /.*
  script: playgrub.py
