application: playgrub
version: 32
runtime: python
api_version: 1

handlers:
- url: /admin/.*
  script: admin.py

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: playgrub.py
