application: playgrub
version: 21
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /.*
  script: playgrub.py
